### PR TITLE
postgresql 12 compatibility, pg_attrdef.adsrc dropped

### PR DESCRIPTION
**Pull request by Ivan-SB**
Since pg_attrdef.adsrc has been finally dropped, current code is not compatible anymore with PostgresQL 12.

pg_get_serial_sequence() and pg_get_expr were supported from version prior to 8.2.
One of the queries has been completely rewritten to use information_schema that is part of SQL standard.

My only concern is that original query returned default values for sequences with the schema specifier prefixed, while new incarnation return it without schema

eg.

nextval('horde_alarms_id_seq'::regclass)

vs.

nextval('public.horde_alarms_id_seq'::regclass)

Behavior could be changed emptying schema_path but this shouldn't be a concern because the sequence should already be there and unless Horde somewhere change search_path or create sequences with the same name in 2 different schema, postgresql will refer to the correct sequence.

I'd like to tank Tom Lane (tgl@openvistas.net) and Laurenz Albe (laurenz.albe@cybertec.at) for their help.

### CODE REVIEW

**Comment by Ivan-SB** [comment]
ping...

**Comment by yunosh** [comment]
Can you please rebase it, now that we have working tests again and also test different PostgreSQL versions?

**Comment by amessina** [comment]
Thank you for your work on this, though there may be other issues.  The following is when adding an event in Kronolith:
```
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  SELECT setval('horde_queue_tasks_task_id_seq', (SELECT COALESCE(MAX("event_id") + (SELECT
    increment_by FROM pg_sequences where schemaname= ANY
    (CURRENT_SCHEMAS(false)) and sequencename='horde_queue_tasks_task_id_seq'), (SELECT min_value FROM
    pg_sequences where schemaname= ANY (CURRENT_SCHEMAS(false)) and
    sequencename='horde_queue_tasks_task_id_seq')) FROM "kronolith_events"), false)
```

**Comment by amessina** [comment]
> Thank you for your work on this, though there may be other issues. The following is when adding an event in Kronolith:
> 
> ```
> HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
> STATEMENT:  SELECT setval('horde_queue_tasks_task_id_seq', (SELECT COALESCE(MAX("event_id") + (SELECT
>     increment_by FROM pg_sequences where schemaname= ANY
>     (CURRENT_SCHEMAS(false)) and sequencename='horde_queue_tasks_task_id_seq'), (SELECT min_value FROM
>     pg_sequences where schemaname= ANY (CURRENT_SCHEMAS(false)) and
>     sequencename='horde_queue_tasks_task_id_seq')) FROM "kronolith_events"), false)
> ```

This seems to be that the `kronolith_events` table has random strings for `event_id` such as `4-2B-rcjiu79ApLtMxwSYQ1` -- not sure how this worked before but text+integer won't work and in the Kronolith case.  It seems like tables that don't have autoincrement pkeys need to be excluded here.  I'm no expert at Horde's original design for PostgreSQL, but I can't see the seq_id is necessary or what it's used for.

**Comment by Ivan-SB** [comment]
On 5/4/20 4:41 AM, Anthony Messina wrote:
>     Thank you for your work on this, though there may be other issues.
>     The following is when adding an event in Kronolith:
> 
>     |HINT: No operator matches the given name and argument types. You
>     might need to add explicit type casts. STATEMENT: SELECT
>     setval('horde_queue_tasks_task_id_seq', (SELECT
>     COALESCE(MAX("event_id") + (SELECT increment_by FROM pg_sequences
>     where schemaname= ANY (CURRENT_SCHEMAS(false)) and
>     sequencename='horde_queue_tasks_task_id_seq'), (SELECT min_value
>     FROM pg_sequences where schemaname= ANY (CURRENT_SCHEMAS(false)) and
>     sequencename='horde_queue_tasks_task_id_seq')) FROM
>     "kronolith_events"), false) |
> 
> This seems to be that the |kronolith_events| table has random strings 
> for |event_id| such as |4-2B-rcjiu79ApLtMxwSYQ1| -- not sure how this 
> worked before but text+integer won't work and in the Kronolith case. It 
> seems like tables that don't have autoincrement pkeys need to be 
> excluded here. I'm no expert at Horde's original design for PostgreSQL, 
> but I can't see the seq_id is necessary or what it's used for.

I'd give it a look. I've never come across any error coming from this 
query and I've been using my "patched" version of horde for several 
months with pgsql12.

But surely enough it is going to fail since as you noticed 
kronolith_events.event_id doesn't contain numbers.

Where did you find that query?

thanks

-- 
Ivan Sergio Borgonovo
https://www.webthatworks.it https://www.borgonovo.net

**Comment by amessina** [comment]
I had been using the previous patch for PostgreSQL 10 through 11 without any warnings.  After upgrading with pg_upgrade to PostgreSQL 12, I began seeing these.

That query originates  when I click "Save" upon creating an event in Kronolith.

**Comment by Ivan-SB** [comment]
On 5/4/20 3:14 PM, Anthony Messina wrote:
> I had been using the previous patch for PostgreSQL 10 through 11 without 
> any warnings. After upgrading with pg_upgrade to PostgreSQL 12, I began 
> seeing these.
> 
> That query originates when I click "Save" upon creating an event in 
> Kronolith.

I can't observe the same problem.

I grep a bit in the source code but I wasn't able to find the query.
But I've been doing it in my debian sid install and source code is 
spread across different path and I'm not sure I got them all.

I'll try to check better soon


-- 
Ivan Sergio Borgonovo
https://www.webthatworks.it https://www.borgonovo.net

**Comment by amessina** [comment]
@Ivan-SB I got my issue squared away and can confirm that your updates work with PostgreSQL 12.  I apologize if my issue created extra noise for you.

For some reason I'll never know (something during the upgrade from PG 11 to PG 12), the `horde_queue_tasks_task_id_seq` sequence was associated with the `kronolith_events` table:
```
horde=# select seq_ns.nspname as sequence_schema,
horde-#        seq.oid as sequence_oid,
horde-#        seq.relname as sequence_name,
horde-#        tab_ns.nspname as table_schema,
horde-#        tab.relname as related_table
horde-# from pg_class seq
horde-#   join pg_namespace seq_ns on seq.relnamespace = seq_ns.oid
horde-#   JOIN pg_depend d ON d.objid = seq.oid AND d.deptype = 'a' 
horde-#   JOIN pg_class tab ON d.objid = seq.oid AND d.refobjid = tab.oid
horde-#   JOIN pg_namespace tab_ns on tab.relnamespace = tab_ns.oid
horde-# where seq.relkind = 'S' 
horde-#   and seq.relname = 'horde_queue_tasks_task_id_seq'
horde-#   and seq_ns.nspname = 'public';
 sequence_schema | sequence_oid |         sequence_name         | table_schema |   related_table   
-----------------+--------------+-------------------------------+--------------+-------------------
 public          |        17037 | horde_queue_tasks_task_id_seq | public       | kronolith_events
 public          |        17037 | horde_queue_tasks_task_id_seq | public       | horde_queue_tasks
(2 rows)
```
After deleting and recreating the `horde_queue_tasks` and `horde_queue_schema` tables (which deleted the `horde_queue_tasks_task_id_seq` sequence), I recreated the Horde_Queue tables from the web interface and I see no issues and the `horde_queue_tasks_task_id_seq` sequence is only related to the `horde_queue_tasks` table.

```
horde=# select seq_ns.nspname as sequence_schema,
       seq.oid as sequence_oid,
       seq.relname as sequence_name,
       tab_ns.nspname as table_schema,
       tab.relname as related_table
from pg_class seq
  join pg_namespace seq_ns on seq.relnamespace = seq_ns.oid
  JOIN pg_depend d ON d.objid = seq.oid AND d.deptype = 'a' 
  JOIN pg_class tab ON d.objid = seq.oid AND d.refobjid = tab.oid
  JOIN pg_namespace tab_ns on tab.relnamespace = tab_ns.oid
where seq.relkind = 'S' 
  and seq.relname = 'horde_queue_tasks_task_id_seq'
  and seq_ns.nspname = 'public';
 sequence_schema | sequence_oid |         sequence_name         | table_schema |   related_table   
-----------------+--------------+-------------------------------+--------------+-------------------
 public          |       249536 | horde_queue_tasks_task_id_seq | public       | horde_queue_tasks
```

**Comment by Ivan-SB** [comment]
ping...

**Comment by speachy** [comment]
I just got bitten by this too.  The patch fixed it on my system.

**Pull request merged**
